platform(
    name = "platform",
    constraint_values = [
        "@platforms//os:none",
        "@platforms//cpu:arm",

    ],
    # parents = [],
    # remote_execution_properties = "",
    # tags = [""],
    # visibility = [""],
)